Regions = [
('NA', 'North Africa'),
('EA', 'East Africa'),
('SA', 'South Africa'),
('CA', 'Central Africa'),
('WA', 'West Africa'),
('DA', 'African Diaspora'),
]
 
NA = [
('AF', 'Afghanistan'),
('DZ', 'Algeria'),
('CY', 'Cyprus'),
('EG', 'Egypt'),
('IQ', 'Iraq'),
('IL', 'Israel'),
('KW', 'Kuwait'),
('LB', 'Lebanon'),
('LY', "Libya"),
('MT', 'Malta'),
('MR', 'Mauritania'),
('MA', 'Morocco'),
('OM', 'Oman'),
('PS', 'Palestine, State of'),
('QA', 'Qatar'),
('SA', "Saudi Arabia"),
('SY', 'Syrian Arab Republic'),
('TN', 'Tunisia'),
('AE', 'United Arab Emirates (the)'),
('YE', 'Yemen'),
]

EA = [
('BI', 'Burundi'),
('IO', 'British Indian Ocean Territory (the)'),
('DJ', 'Djibouti'),
('ER', 'Eritrea'),
('ET', 'Ethiopia'),
('KE', 'Kenya'),
('RW', 'Rwanda'),
('SO', 'Somalia'),
('SS', 'South Sudan'),
('SD', 'Sudan (the)'),
('TZ', 'Tanzania, United Republic of'),
('UG', 'Uganda'),
]

SA = [
('AO', 'Angola'),
('BW', 'Botswana'),
('KM', 'Comoros (the)'),
('SZ', 'Eswatini'),
('TF', 'French Southern Territories (the)'),
('HM', 'Heard Island and McDonald Islands'),
('LS', 'Lesotho'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MZ', 'Mozambique'),
('NA', 'Namibia'),
('RE', 'Réunion'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
('SC', 'Seychelles'),
('ZA', 'South Africa'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe'),
]

CA = [
('CM', 'Cameroon'),
('CF', 'Central African Republic (the)'),
('TD', 'Chad'),
('CD', 'Congo (the Democratic Republic of the)'),
('CG', 'Congo (the)'),
('GQ', 'Equatorial Guinea'),
('GA', 'Gabon'),
('ST', 'Sao Tome and Principe'),
]

WA = [
('BJ', 'Benin'),
('BF', 'Burkina Faso'),
('CV', 'Cabo Verde'),
('CI', "Côte d'Ivoire"),
('GM', 'Gambia (the)'),
('GH', 'Ghana'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('LR', 'Liberia'),
('ML', 'Mali'),
('NE', 'Niger (the Republic of)'),
('NG', 'Nigeria'),
('SN', 'Senegal'),
('SL', 'Sierra Leone'),
('TG', 'Togo'),
('EH', 'Western Sahara'),
]

DA = [
('AT', 'Atlantis'),
('AA', 'Australasia'),
('CR', 'Carribean'),
('CM', 'Central America'),
('ER', 'Eurasia'),
('NM', 'North America'),
('OC', 'Oceania'), #formally Lemuria before it sank
('SM', 'South America'),
]
 
CR = [
('AI', 'Anguilla'),
('AG', 'Antigua and Barbuda'),
('AW', 'Aruba'),
('BS', 'Bahamas (the)'),
('BB', 'Barbados'),
('BM', 'Bermuda'),
('BQ', 'Bonaire, Sint Eustatius and Saba'),
('KY', 'Cayman Islands (the)'),
('CU', 'Cuba'),
('CW', 'Curaçao'),
('DM', 'Dominica'),
('DO', 'Dominican Republic (the)'),
('GD', 'Grenada'),
('GP', 'Guadeloupe')
('HT', 'Haiti'),
('JM', 'Jamaica'),
('MQ', 'Martinique'),
('MS', 'Montserrat'),
('PR', 'Puerto Rico'),
('BL', 'Saint Barthélemy'),
('KN', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia'),
('MF', 'Saint Martin (French part)'),
('PM', 'Saint Pierre and Miquelon'),
('VC', 'Saint Vincent and the Grenadines'),
('SX', 'Sint Maarten (Dutch part)'),
('SR', 'Suriname'),
('TT', 'Trinidad and Tobago'),
('TC', 'Turks and Caicos Islands (the)'),
('UM', 'United States Minor Outlying Islands (the)'),
('VG', 'Virgin Islands (British)'),
('VI', 'Virgin Islands (U.S.)'),
]
  
AA = [
('AU', 'Australia'),
('BN', 'Brunei Darussalam'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands (the)'),
('ID', 'Indonesia'),
('NZ', 'New Zealand'),
('NF', 'Norfolk Island'),
('PW', 'Palau'),
('PG', 'Papua New Guinea'),
('SB', 'Solomon Islands'),
('TL', 'Timor-Leste'),
('VU', 'Vanuatu'),
]

CM = [
('CR', 'Costa Rica'),
('SV', 'El Salvador'),
('GT', 'Guatemala'),
('HN', 'Honduras'),
('MX', 'Mexico'),
('NI', 'Nicaragua'),
('PA', 'Panama'),
]

ER = [
('AL', 'Albania'),
('AD', 'Andorra'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BT', 'Bhutan'),
('BA', 'Bosnia and Herzegovina'),
('BV', 'Bouvet Island'),
('BG', 'Bulgaria'),
('KH', 'Cambodia'),
('CN', 'China'),
('HR', 'Croatia'),
('CZ', 'Czechia'),
('DK', 'Denmark'),
('EE', 'Estonia'),
('FO', 'Faroe Islands (the)'),
('FI', 'Finland'),
('FR', 'France'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GG', 'Guernsey'),
('VA', 'Holy See (the)'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('IR', 'Iran (Islamic Republic of)'),
('IE', 'Ireland'),
('IM', 'Isle of Man'),
('IT', 'Italy'),
('JP', 'Japan'),
('JE', 'Jersey'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KP', "Korea (the Democratic People's Republic of)"),
('KR', 'Korea (the Republic of)'),
('KG', 'Kyrgyzstan'),
('LA', "Lao People's Democratic Republic (the)"),
('LV', 'Latvia'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('MD', 'Moldova (the Republic of)'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MM', 'Myanmar'),
('NP', 'Nepal'),
('NL', 'Netherlands (the)'),
('NC', 'New Caledonia'),
('NO', 'Norway'),
('PK', 'Pakistan'),
('PH', 'Philippines (the)'),
('PL', 'Poland'),
('PT', 'Portugal'),
('MK', 'Republic of North Macedonia'),
('RO', 'Romania'),
('RU', 'Russian Federation (the)'),
('SM', 'San Marino'),
('RS', 'Serbia'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SJ', 'Svalbard and Jan Mayen'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('TW', 'Taiwan'),
('TJ', 'Tajikistan'),
('TH', 'Thailand'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('UA', 'Ukraine'),
('GB', 'United Kingdom of Great Britain and Northern Ireland (the)'),
('UZ', 'Uzbekistan'),
('VN', 'Viet Nam'),
('AX', 'Åland Islands')
]

NM = [
('CA', 'Canada'),
('US', 'United States of America (the)'),
]

OC = [
('AS', 'American Samoa'),
('CK', 'Cook Islands (the)'),
('FJ', 'Fiji'),
('PF', 'French Polynesia'),
('GU', 'Guam'),
('KI', 'Kiribati'),
('MH', 'Marshall Islands (the)'),
('FM', 'Micronesia (Federated States of)'),
('NR', 'Nauru'),
('NU', 'Niue'),
('MP', 'Northern Mariana Islands (the)'),
('PN', 'Pitcairn'),
('WS', 'Samoa'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TV', 'Tuvalu'),
('WF', 'Wallis and Futuna'),
]

SM = [
('BZ', 'Belize'),
('BO', 'Bolivia (Plurinational State of)'),
('BR', 'Brazil'),
('CL', 'Chile'),
('CO', 'Colombia'),
('EC', 'Ecuador'),
('FK', 'Falkland Islands (the) '),
('GF', 'French Guiana'),
('GY', 'Guyana'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('GS', 'South Georgia and the South Sandwich Islands'),
('UY', 'Uruguay'),
('VE', 'Venezuela (Bolivarian Republic of)'),
]
 
continents = [
('AF', 'Africa'),
('AT', 'Atlantis'),
('AA', 'Australasia'),
('CR', 'Carribean'),
('CM', 'Central America'),
('ER', 'Eurasia'),
('NM', 'North America'),
('OC', 'Oceania'), #formally Lemuria before it sank
('SM', 'South America'),
]

 
territories = [
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas (the)'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia (Plurinational State of)'),
('BQ', 'Bonaire, Sint Eustatius and Saba'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BV', 'Bouvet Island'),
('BR', 'Brazil'),
('IO', 'British Indian Ocean Territory (the)'),
('BN', 'Brunei Darussalam'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('CV', 'Cabo Verde'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('KY', 'Cayman Islands (the)'),
('CF', 'Central African Republic (the)'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands (the)'),
('CO', 'Colombia'),
('KM', 'Comoros (the)'),
('CD', 'Congo (the Democratic Republic of the)'),
('CG', 'Congo (the)'),
('CK', 'Cook Islands (the)'),
('CR', 'Costa Rica'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CW', 'Curaçao'),
('CY', 'Cyprus'),
('CZ', 'Czechia'),
('CI', "Côte d'Ivoire"),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic (the)'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('SZ', 'Eswatini'),
('ET', 'Ethiopia'),
('FK', 'Falkland Islands (the) '),
('FO', 'Faroe Islands (the)'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GF', 'French Guiana'),
('PF', 'French Polynesia'),
('TF', 'French Southern Territories (the)'),
('GA', 'Gabon'),
('GM', 'Gambia (the)'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GD', 'Grenada'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HM', 'Heard Island and McDonald Islands'),
('VA', 'Holy See (the)'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran (Islamic Republic of)'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IM', 'Isle of Man'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JE', 'Jersey'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', "Korea (the Democratic People's Republic of)"),
('KR', 'Korea (the Republic of)'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', "Lao People's Democratic Republic (the)"),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', "Libya"),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands (the)'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MX', 'Mexico'),
('FM', 'Micronesia (Federated States of)'),
('MD', 'Moldova (the Republic of)'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands (the)'),
('NC', 'New Caledonia'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger (the Republic of)'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Norfolk Island'),
('MP', 'Northern Mariana Islands (the)'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PS', 'Palestine, State of'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines (the)'),
('PN', 'Pitcairn'),
('PL', 'Poland'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('MK', 'Republic of North Macedonia'),
('RO', 'Romania'),
('RU', 'Russian Federation (the)'),
('RW', 'Rwanda'),
('RE', 'Réunion'),
('BL', 'Saint Barthélemy'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha'),
('KN', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia'),
('MF', 'Saint Martin (French part)'),
('PM', 'Saint Pierre and Miquelon'),
('VC', 'Saint Vincent and the Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome and Principe'),
('SA', "Saudi Arabia"),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SX', 'Sint Maarten (Dutch part)'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('GS', 'South Georgia and the South Sandwich Islands'),
('SS', 'South Sudan'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan (the)'),
('SR', 'Suriname'),
('SJ', 'Svalbard and Jan Mayen'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syrian Arab Republic'),
('TW', 'Taiwan'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania, United Republic of'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TC', 'Turks and Caicos Islands (the)'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates (the)'),
('GB', 'United Kingdom of Great Britain and Northern Ireland (the)'),
('UM', 'United States Minor Outlying Islands (the)'),
('US', 'United States of America (the)'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela (Bolivarian Republic of)'),
('VN', 'Viet Nam'),
('VG', 'Virgin Islands (British)'),
('VI', 'Virgin Islands (U.S.)'),
('WF', 'Wallis and Futuna'),
('EH', 'Western Sahara'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe'),
('AX', 'Åland Islands')]
 
