# Generated by Django 2.2.28 on 2023-09-02 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('repeat', models.CharField(blank=True, max_length=10, null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FBMPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('radius', models.CharField(blank=True, max_length=50, null=True)),
                ('angle', models.CharField(blank=True, max_length=3, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('otype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nounce', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('hashKey', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LLPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('otype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('hashKey', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MMPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('radius', models.CharField(blank=True, max_length=50, null=True)),
                ('angle', models.CharField(blank=True, max_length=3, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('otype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('repeat', models.CharField(blank=True, max_length=10, null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('repeat', models.CharField(blank=True, max_length=10, null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Corre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbmpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hantu.FBMPoint')),
                ('llpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hantu.LLPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Corre0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbmpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hantu.FBMPoint')),
                ('mmpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hantu.MMPoint')),
            ],
        ),
    ]
