# Generated by Django 2.2.6 on 2022-04-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosebedisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('pkn', models.BigIntegerField(default=0)),
                ('pke', models.BigIntegerField(default=0)),
            ],
        ),
    ]
