# Generated by Django 2.2.28 on 2022-11-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('mosebedisi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Mosebedisi')),
                ('picture', models.FileField(upload_to='')),
                ('female', models.BooleanField(default=True)),
                ('Status', models.CharField(choices=[('SI', 'single'), ('IR', 'in committed relationship'), ('MA', 'married'), ('SP', 'separated'), ('DV', 'divorced'), ('WI', 'widowed')], default='SI', max_length=2)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mosebedisi',
            name='pke',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='mosebedisi',
            name='pkn',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
