# Generated by Django 2.2.6 on 2022-12-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221119_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(upload_to='')),
                ('story', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.FileField(upload_to='')),
                ('msg_type', models.CharField(choices=[('TE', 'text'), ('VN', 'voice note'), ('IM', 'image'), ('VI', 'video')], default='TE', max_length=2)),
                ('signature', models.FileField(upload_to='')),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=True)),
                ('group', models.ManyToManyField(to='home.Group')),
                ('mosebedisi', models.ManyToManyField(to='home.Mosebedisi')),
            ],
        ),
    ]
