# Generated by Django 2.2.28 on 2023-02-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('story', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mosebedisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('mosebedisi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='muntu.Mosebedisi')),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('female', models.BooleanField(default=True)),
                ('Status', models.CharField(choices=[('SI', 'single'), ('IR', 'in committed relationship'), ('MA', 'married'), ('SP', 'separated'), ('DV', 'divorced'), ('WI', 'widowed')], default='SI', max_length=2)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=True)),
                ('group', models.ManyToManyField(to='muntu.Group')),
                ('mosebedisi', models.ManyToManyField(to='muntu.Mosebedisi')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.FileField(blank=True, null=True, upload_to='')),
                ('msg_type', models.CharField(choices=[('TE', 'text'), ('VN', 'voice note'), ('IM', 'image'), ('VI', 'video')], default='TE', max_length=2)),
                ('signature', models.FileField(blank=True, null=True, upload_to='')),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntu.Profile')),
            ],
        ),
    ]
