# Generated by Django 2.2.6 on 2023-07-08 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone0', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('dependant', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=datetime.date(2023, 7, 8))),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('NF', 'Nuclear family'), ('EF', 'Extended family'), ('Cl', 'Clan'), ('Tr', 'Tribe'), ('Na', 'Nation'), ('Fr', 'Friends'), ('Co', 'Company'), ('Msg', 'Messages'), ('Reg', 'Region'), ('C', 'Country')], default='NF', max_length=3),
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('member', models.ManyToManyField(to='muntu.Member')),
                ('milestone2', models.ManyToManyField(to='muntu.MileStone')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('achievement', models.ManyToManyField(to='muntu.Achievement')),
                ('milestone4', models.ManyToManyField(to='muntu.MileStone')),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(blank=True, max_length=100, null=True)),
                ('need_type', models.CharField(choices=[('SK', 'Self-knowledge'), ('SO', 'Sociological'), ('PH', 'Physical')], default='PH', max_length=2)),
                ('due_date', models.DateField(default=datetime.date(2023, 7, 8))),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntu.Group')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntu.Need'),
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified', models.BooleanField(default=False)),
                ('memeber', models.ManyToManyField(to='muntu.Member')),
                ('milestone3', models.ManyToManyField(to='muntu.MileStone')),
            ],
        ),
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField(auto_now_add=True)),
                ('location_latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('location_longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('verifier_pkn', models.CharField(default='0', max_length=50)),
                ('verifier_pke', models.CharField(default='0', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('achievement', models.ManyToManyField(to='muntu.Achievement')),
                ('profile', models.ManyToManyField(to='muntu.Profile')),
            ],
        ),
    ]
