# Generated by Django 2.2.6 on 2023-07-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0002_auto_20230708_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='milestone3',
            new_name='milestone',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='milestone0',
            new_name='milestone',
        ),
        migrations.RenameField(
            model_name='qualificationrequirements',
            old_name='milestone4',
            new_name='milestone',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='milestone2',
            new_name='milestone',
        ),
    ]
