# Generated by Django 2.2.6 on 2023-07-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0003_auto_20230708_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='memeber',
            new_name='member',
        ),
    ]
