# Generated by Django 2.2.28 on 2023-09-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0004_auto_20230708_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nounce', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('hashKey', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='mosebedisi',
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='muntu.Mosebedisi'),
        ),
        migrations.AlterField(
            model_name='member',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='muntu.Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='signature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='muntu.Group')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='muntu.Mosebedisi')),
                ('person', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='muntu.Mosebedisi')),
            ],
        ),
        migrations.CreateModel(
            name='LTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('CI', 'Clock In'), ('CO', 'Clock Out'), ('LS', 'Lunch Start'), ('LE', 'Lunch End')], default='CO', max_length=2)),
                ('hashKey', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('mosebedisi', models.ManyToManyField(to='muntu.Mosebedisi')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='muntu.Membership', to='muntu.Mosebedisi'),
        ),
    ]
