# Generated by Django 2.2.6 on 2023-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0006_auto_20230902_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ManyToManyField(related_name='request_receiver', to='muntu.Mosebedisi')),
                ('sender', models.ManyToManyField(to='muntu.Mosebedisi')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('friend', models.ManyToManyField(related_name='friend', to='muntu.Mosebedisi')),
                ('user', models.ManyToManyField(to='muntu.Mosebedisi')),
            ],
        ),
    ]
