# Generated by Django 2.2.6 on 2023-10-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0007_contact_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntu.Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muntu.Mosebedisi'),
        ),
    ]
