# Generated by Django 2.2.28 on 2024-08-17 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0011_auto_20240525_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user0_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('user1_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('secret', models.TextField(blank=True, null=True)),
                ('nonce', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='female',
        ),
        migrations.AddField(
            model_name='contact',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='nonce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever_addr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_addr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosebedisi',
            name='address',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ManyToManyField(related_name='request_receiver', to='muntu.Profile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ManyToManyField(to='muntu.Profile'),
        ),
        migrations.AlterField(
            model_name='mosebedisi',
            name='pkn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
