# Generated by Django 2.2.28 on 2024-08-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muntu', '0012_auto_20240817_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='pkn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever_addr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_addr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
