# Generated by Django 2.2.28 on 2023-09-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nounce', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('hashKey', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('pkn', models.CharField(default='0', max_length=150)),
                ('pke', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kintu.Account')),
                ('known_country', models.CharField(blank=True, max_length=100, null=True)),
                ('known_region', models.CharField(blank=True, max_length=100, null=True)),
                ('known_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('upo', models.CharField(blank=True, max_length=100, null=True)),
                ('hashKey', models.CharField(blank=True, max_length=150, null=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver', models.ManyToManyField(related_name='reciever', to='kintu.Account')),
                ('sender', models.ManyToManyField(to='kintu.Account')),
            ],
        ),
    ]
