# Generated by Django 2.2.28 on 2024-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintu', '0002_auto_20231007_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='pke',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='header',
            name='pkn',
            field=models.CharField(default='0', max_length=5000),
        ),
    ]
